apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
spec:
  replicas: 12
  selector:
    matchLabels:
      app: registration-service
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - name: registration-service
        image: szymonpawlica22/registration:latest
        ports:
        - containerPort: 50051