# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_download.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13game_download.proto\x12\rgame_download\"#\n\x0bLinkRequest\x12\x14\n\x0c\x64ownload_key\x18\x01 \x01(\t\"\x1f\n\x0cLinkResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Y\n\x0cGameDownload\x12I\n\x0c\x44ownloadLink\x12\x1a.game_download.LinkRequest\x1a\x1b.game_download.LinkResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_download_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LINKREQUEST._serialized_start=38
  _LINKREQUEST._serialized_end=73
  _LINKRESPONSE._serialized_start=75
  _LINKRESPONSE._serialized_end=106
  _GAMEDOWNLOAD._serialized_start=108
  _GAMEDOWNLOAD._serialized_end=197
# @@protoc_insertion_point(module_scope)
