go.property("dir", vmath.vector3())

function init(self)
	self.speed = 1000
end

local function hit(self)
	self.life = 1000
	self.speed = 0
	-- Need animation for shrapnel
	go.set_rotation(vmath.quat())
	msg.post("#sprite", "play_animation", { id = hash("death") })
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.dir * self.speed * dt
	go.set_position(pos)

	if pos.y > 768 then
		go.delete()
	elseif pos.y < 0 then
		go.delete()
	elseif pos.x > 1280 then
		go.delete()
	elseif pos.x < 0 then
		go.delete()
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("animation_done") then
		go.delete()
	elseif message_id == hash("contact_point_response") then
		hit(self)
		go.delete(message.other_id)
	end
end