# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: achievements.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x63hievements.proto\x12\x0c\x61\x63hievements\"E\n\x18UpdateAchievementRequest\x12\x16\n\x0e\x61\x63hievement_id\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\",\n\x19UpdateAchievementResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2w\n\x0c\x41\x63hievements\x12g\n\x12UpdateAchievements\x12&.achievements.UpdateAchievementRequest\x1a\'.achievements.UpdateAchievementResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'achievements_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPDATEACHIEVEMENTREQUEST._serialized_start=36
  _UPDATEACHIEVEMENTREQUEST._serialized_end=105
  _UPDATEACHIEVEMENTRESPONSE._serialized_start=107
  _UPDATEACHIEVEMENTRESPONSE._serialized_end=151
  _ACHIEVEMENTS._serialized_start=153
  _ACHIEVEMENTS._serialized_end=272
# @@protoc_insertion_point(module_scope)
