# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_download_pb2 as game__download__pb2


class GameDownloadStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDownloadLink = channel.unary_unary(
                '/game_download.GameDownload/GetDownloadLink',
                request_serializer=game__download__pb2.LinkRequest.SerializeToString,
                response_deserializer=game__download__pb2.LinkResponse.FromString,
                )


class GameDownloadServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDownloadLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameDownloadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDownloadLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadLink,
                    request_deserializer=game__download__pb2.LinkRequest.FromString,
                    response_serializer=game__download__pb2.LinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game_download.GameDownload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameDownload(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDownloadLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game_download.GameDownload/GetDownloadLink',
            game__download__pb2.LinkRequest.SerializeToString,
            game__download__pb2.LinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
