# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import purchase_auth_pb2 as purchase__auth__pb2


class PurchaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthorisePurchase = channel.unary_unary(
                '/purchasing.Purchase/AuthorisePurchase',
                request_serializer=purchase__auth__pb2.PurchaseRequest.SerializeToString,
                response_deserializer=purchase__auth__pb2.PurchaseResponse.FromString,
                )


class PurchaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthorisePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PurchaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthorisePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorisePurchase,
                    request_deserializer=purchase__auth__pb2.PurchaseRequest.FromString,
                    response_serializer=purchase__auth__pb2.PurchaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'purchasing.Purchase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Purchase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthorisePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/purchasing.Purchase/AuthorisePurchase',
            purchase__auth__pb2.PurchaseRequest.SerializeToString,
            purchase__auth__pb2.PurchaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
